name: gyansagar
services:
  auth:
    build: ./portfolio-auth-microservice
    ports:
      - "5000:5000"
      - "9229:9229"
    command: npm run dev
    develop:
      watch:
        - action : rebuild
          path : ./portfolio-auth-microservice/package.json

        - action : sync+restart
          path : ./portfolio-auth-microservice
          target : /usr/src/app
          exec : 
            command : npm run dev
    depends_on:
      - mongo-auth
  
  blog:
    build: ./portfolio-blog-microservice
    ports:
      - "5001:5001"
      - "9230:9230"
    command: npm run dev
    develop:
      watch:
        - action : rebuild
          path : ./portfolio-blog-microservice/package.json

        - action : sync+restart
          path : ./portfolio-blog-microservice
          target : /usr/src/app
          exec : 
            command : npm run dev
    depends_on:
      - mongo-blog

  api-gateway:
    image: nginx:1.27.3-bookworm
    depends_on:
      - auth
      - blog
    ports:
      - "8080:80"
    develop:
      watch:
        - action : sync+exec
          path : ./nginx.conf
          target : /etc/nginx/nginx.conf
          exec:
            command : nginx -s reload

  manager-ui:
    image: node:22-alpine3.20
    build:
      context: ./blog-manager-ui
      dockerfile: Dockerfile
      target: builder
    ports:
      - "3000:3000"
    develop:
     watch:
       - action : rebuild
         path : ./blog-manager-ui/package.json

       - action : sync
         path : ./blog-manager-ui
         target : /usr/src/app
    depends_on:
      - auth
      - blog

  mongo-auth:
    image: mongo
    hostname: mongo-auth
    env_file: "./portfolio-auth-microservice/.env"
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./portfolio-auth-microservice/mongo-seed:/docker-entrypoint-initdb.d/

  mongo-blog:
    image: mongo
    env_file: ./portfolio-blog-microservice/.env
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27018:27017"
    volumes:
      - ./portfolio-blog-microservice/mongo-seed:/docker-entrypoint-initdb.d/